pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
            git branch: 'main', url: 'https://github.com/ShilpaLB28/indexfile.git'
            }
        }
        stage('deploy') {
            steps {
                sshagent (['ec2-ssh']) {
                    sh '''
                    scp -o StrictHostKeyChecking=no webapp/index.html ubuntu@3.107.34.25:/tmp/
                    ssh ubuntu@3.107.34.25 "sudo mv /tmp/index.html /var/www/html/"
                    '''
                }
            }
        }
        stage('Restart nginx') {
            steps {
                sshagent (['ec2-ssh']) {
                    sh'''
                    ssh ubuntu@3.107.34.25 "sudo systemsctl restart nginx"
                    ''' 
                }
            }
        }
    }
}